---
RuhohSpec: '0.2'
permalink: /blog/:categories/:title
theme : twitter

production_url : http://username.github.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html

comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

analytics :
  provider : getclicky
  google : 
      tracking_id : 'UA-123-12'
  getclicky :
    site_id : 66563918

syntax :
  provider : google_prettify
  google_prettify : 
      theme: sunburst-custom
      linenums : true
