---
RuhohSpec: '2.0.alpha'

production_url: http://ruhoh.com

"theme-ruhoh" : 
  use : "theme"

docs:
  layout: docs-2

api:
  layout: docs-2

posts:
  permalink: /blog/:categories/:title/

asset_pipeline:
  enable: true

widgets :

  analytics :
    use : getclicky
    # -- config for google --
    # tracking_id : 'UA-123-12'

    # -- config for getclicky  --
    site_id : 66563918

  comments :
    use : disqus
    # -- config for disqus --
    short_name : jekyllbootstrap # Change This!

  google_prettify :
    use : overloaded
    linenums : true
  