---
RuhohSpec: '2.0.alpha'
theme: 
  name: twitter
production_url: http://username.github.com
archive_path: /archive.html
categories_path: /categories.html
tags_path: /tags.html

posts:
  permalink: /blog/:categories/:title/
